# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0002_bot_ipaddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdata',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='smsdata',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='smsdata',
            name='message',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='smsdata',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
