# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0003_auto_20180529_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdata',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='botcommand',
            name='executed',
            field=models.BooleanField(default=False),
        ),
    ]
