# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0004_auto_20180529_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcommand',
            name='parameters',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
