# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0005_auto_20180529_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('type', models.IntegerField()),
                ('type_str', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('ipaddr', models.CharField(max_length=15)),
                ('call', models.CharField(max_length=20)),
                ('raw_msg', models.CharField(max_length=1024, null=True)),
                ('decoded_msg', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='botcommand',
            name='parameters',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
