# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0007_auto_20180529_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnc.Bot'),
        ),
    ]
