# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0009_botcommand_deployed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcommand',
            name='deployed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
